### ISSUE TITLE
New feature: Compare new image submissions to locally saved images

### ISSUE THREAD

**Issue by elijaholmos** [Leyline-gg/leyline-discord#104]
**Issue blocked to due to lack of free/easy-to-use resources. External assistance would be appreciated!**

- Whenever a good-acts photo is submitted, the bot should first check if it matches any previously submitted photos in the database
  - Common falsification techniques that should be caught:
    - Image resizing
    - Image cropping (to remove background items)
    - Altering hue/saturation/tint
  - Determine a threshold to avoid false positives
  - Notification for images above threshold will be added to the embed that is sent in the good-acts message's thread
- ~~Whenever a good-acts photo/video is submitted, store the file in a database (only if the above check is passed)~~ **implemented w/ #125** 
  - ~~Probably a local cache for the beginning~~
 
Resources:
https://deepai.org/machine-learning-model/image-similarity (fee associated)
https://www.npmjs.com/package/opencv4nodejs (Complicated install process)

**Comment by elijaholmos** [comment]
Moving to blocked. DeepAI has fees associated with their API. OpenCV has a complicated install process that is difficult to setup on my local machine, which I doubt will be any easier on the bot's VM. I searched briefly for other results, but there're limited resources out there that meet the requirements of this issue.

**Comment by kharaone** [comment]
Wondering if we could leverage a more "low tech" algorithm first : https://github.com/juvian/discord-image-dupe
dunno how blockhash algo used here works against a resized or transformed image

**Comment by elijaholmos** [comment]
@kharaone  I think it's worth implementing as a starter approach. looking at [blockhash](https://github.com/commonsmachinery/blockhash-js), it appears to have not been updated in nearly 5 years, but it is free to use & easy to setup. ideally we would end up shifting to a more up-to-date algorithm that factors in image cropping/resizing

**Comment by kharaone** [comment]
agreed, but such algorithm either needs to be paid, or created from scratch through ML AI. which in itself makes it even more complex and time consuming for something that is a only quality of life for moderators.

Unless we get a student or something who'd like to tackle that one.

@elijaholmos actually, dHash works fine with cropping, rotation, brightness, resolution variations. So it could be a quick win

**Comment by elijaholmos** [comment]
@kharaone oh really? that sounds promising; can you link me to their repo?

**Comment by kharaone** [comment]
There are a few, here’s one : https://github.com/pwlmaciejewski/imghash

Envoyé de mon iPhone

**Comment by elijaholmos** [comment]
Hm I like what I see, thank you. After the PoG API is released I want to revisit this issue.
