### ISSUE TITLE
UnknownMessage error related to good-acts submissions being removed

### ISSUE THREAD

**Issue by elijaholmos** [Leyline-gg/leyline-discord#76]
Mee6 is auto-removing messages sent in good-acts due to a new restriction instituted. Unfortunately, because both Mee6 and Leyline are bots, Leyline is detecting the message creation and creating a new GoodActsReactionCollector for messages that are being deleted. Develop a fix to prevent GoodActsReactionCollectors from being created & backed up to the cloud if Mee6 auto deletes them, OR find a workaround to the mee6 implementation

**Comment by elijaholmos** [comment]
The solution to this is annoying to solve, and I'm fine dealing with the console spam for the time being

**Comment by kharaone** [comment]
@elijaholmos does mee6 need to be on that channel ? aren't we having that channel only for submission ?

**Comment by elijaholmos** [comment]
@kharaone  Mee6 is currently being used exclusively to limit each user's messages to 1 every 24 hours. In all honesty, it is not necessary if I were to rewrite the same functionality in the Leyline bot... this would also remove the console errors that are related to this issue
